"""add profile fields

Revision ID: a2e04e61edd1
Revises: e7d1b2a3c4f5
Create Date: 2026-04-16 21:54:19.353062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e04e61edd1'
down_revision = 'e7d1b2a3c4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nome_instituicao', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nome_instituicao')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
